### ISSUE TITLE
mixed content

### ISSUE THREAD

**Issue by elsdvlee** [kg-construct/rml-lv#10]
E.g. json content in a CSV file > switch reference formulation on field level. 
Concrete examples needed + declarative description to be elaborated.

**Comment by bjdmeest** [comment]
example test case:

| name | config |
|-|-|
| Ben | { "id": "1234", "role": "researcher" } |

I want RDF

```turtle
<#1234> foaf:name "Ben" ;
    a ex:researcher .
```
