### ISSUE TITLE
structural annotation iriSafe

### ISSUE THREAD

**Issue by elsdvlee** [kg-construct/rml-lv#11]
The structural annotation `iriSafe` might influence the output. We need to investigate this further and have test case to see whether it influences the output. The other structural annotations are 'only' optimization hints.

**Comment by bjdmeest** [comment]
| id |
|-|
| Ben De Meester | 
| BenDM |

is the output using `id.iriSafe = true` (so incorrect turtle ⚡ but fast )

```
<Ben De Meester> a foaf:Person .
<BenDM> a foaf:Person .
```

and the output using `id.iriSafe = false` (increasing processing ⚡ but correct turtle )

```
<Ben%20De%20Meester> a foaf:Person .
<BenDM> a foaf:Person .
```

**Comment by bjdmeest** [comment]
Davide's input: should not influence the output at all, even if the annotation is wrong

**Comment by tirrolo** [comment]
See "Invariance Principle" section in pull request by tirrolo: https://github.com/kg-construct/rml-lv/pulls
