### ISSUE TITLE
rml:Field needs some properties of rml:Source

### ISSUE THREAD

**Issue by elsdvlee** [kg-construct/rml-lv#34]
`rml:Field `needs some properties of `rml:Source`, especially when switching reference formulation, e.g. `rml:null` and the seperator specification for CSVW.

**Comment by pmaria** [comment]
Discussed with @elsdvlee and @DylanVanAssche .

We can solve this by introducing more specific descriptions for reference formulations, like is also done for [namespaces and `rml:XPathReferenceFormulation`](https://w3id.org/rml/io/spec#reference-formulations).

An example of what this could look like

```turtle
[]
  rml:logicalSource [
    rml:source [
      rml:root rml:MappingDirectory
      rml:path "data.csv" ;
    ] ;
    rml:referenceFormulation [
      a rml:CsvReferenceFormulation ;
      rml:option [
        rml:null "" ; 
      ] ;
      rml:csvwTableSchema [
        a csvw:TableSchema ;
        csvw:columns ( "id" "name" "age" ) ;
      ] ;
      rml:csvwDialect [
        a csvw:Dialect ;
        csvw:delimiter ";" ;
        csvw:quoteChar "\"" ;
        csvw:escapeChar "\\" ;
        csvw:commentChar "#" ;
        csvw:header false ;
        csvw:skipRows 1 ;
      ] ;
    ] ;
  ] ;
```

We will raise an an issue for this at [rml-io-registry](https://github.com/kg-construct/rml-io-registry/).
