### ISSUE TITLE
rml:onLogicalSource instead of rml:logicalSource

### ISSUE THREAD

**Issue by elsdvlee** [kg-construct/rml-lv#7]
Agreement reached with the participant of the TF meeting on 10/1/2024. 
Broader agreement still needed.

**Comment by bjdmeest** [comment]
Property | Domain | Range
-- | -- | --
rml:onLogicalSource | rml:LogicalView | rml:LogicalSource

Otherwise you have the ambiguity of logicalSource having 2 domains: triplesmap or logicalView, or there's ambiguity between triplesmaps and logicalview definitions

**Comment by elsdvlee** [comment]
**Notes of discussion TF meeting 7/02/2024:** 
We keep the idea that we don't change the domain for the n `rml:logicalSource` property. Its domain remains`rml:TriplesMap` and  we introduce a new property to connect `rml:LogicalSource` to `rml:LogicalView`

This brings on to choosing one among the following properties (subject to easily understandable property name):
- onLogicalSource (might be confusing, might lead to errors because close to logicalSource)
- populatedBy
- viewOnLogicalSource

**Comment by pmaria** [comment]
a shorter alternative: `rml:viewOn`

**Comment by elsdvlee** [comment]
Other alternative: `rml:source` and reconsider `rml:LogicalView` as a subclass of a `rml:LogicalSource` [issues #14](https://github.com/kg-construct/rml-lv/issues/14)

**Comment by elsdvlee** [comment]
awaiting decision on <https://github.com/kg-construct/rml-lv/issues/14> before we can fix and close.

**Comment by elsdvlee** [comment]
See https://github.com/kg-construct/rml-lv/issues/14: agreement to use `rml:viewOn`
